[settings]
lockfile = true
experimental = true

[tools]
uv = "latest"
kubectl = "1.34.7"
helm = "4.1.4"
bun = "latest"
hk = { version = "latest", postinstall = "hk install --mise" }
pkl = "latest"
helm-docs = "latest"
pitchfork = "latest"

# [deps.skills]
# sources = ["skills-lock.json"]
# outputs = [".agent/skills/"]
# run = "bunx skills experimental_install"

[env]
HK_MISE = 1

[tasks.gen-helm-pipeline]
run = """
uv run --directory app/pipeline/scripts generate_pipeline.py --helm > \
    chart/templates/pipeline.yaml
"""

[tasks.gen-helm-docs]
run = "helm-docs --chart-search-root=chart"

[tasks.gen-runtime-requirements]
run = "uv --directory app/runtime pip compile pyproject.toml -o requirements.txt"
